version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - public
      - private
  redis:
    image: redis:4.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - public
      - private
  taskflow:
    image: taskflow:latest
    container_name: taskflow
    networks:
      - public
      - private
    volumes:
      - .:/taskflow
    command: ["supervisord","-c","/taskflow/supervisord.conf"]
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

networks:
  public:
    driver: bridge
  private:
    driver: bridge

