version: '3'

services:
  taskredis:
    image: redis:4.0
    container_name: task-redis
    ports:
      - "6379:6379"
  taskdb:
    image: mysql:8.0
    container_name: task-db
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
  taskservice:
    image: taskflow:latest
    container_name: task-service
    environment:
      DOCKER_HOST: ${HOSTNAME}
    volumes:
      - .:/taskflow
      - ./supervisord.conf:/etc/supervisord.conf
    command: ["supervisord"]
    depends_on:
      - taskredis
      - taskdb
    links:
      - taskredis
      - taskdb

