version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
  redis:
    image: redis:4.0
    container_name: redis
    ports:
      - "6379:6379"
  taskflow:
    image: taskflow:latest
    container_name: taskflow
    volumes:
      - .:/taskflow
    command: ["supervisord","-c","/taskflow/supervisord.conf"]
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

