version: '3'

services:
  task-redis:
    image: redis:4.0
    container_name: task-redis
    ports:
      - "6379:6379"
  task-db:
    image: mysql:8.0
    container_name: task-db
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
  task-service:
    image: taskflow:latest
    container_name: task-service
    volumes:
      - .:/taskflow
      - ./supervisord.conf:/etc/supervisord.conf
    command: ["supervisord"]
    depends_on:
      - task-redis
      - task-db
    links:
      - task-redis
      - task-db

