name: build-image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Files
      run: ls -l
    - name: Build the Docker image
      run: docker build taskflow --file Dockerfile --tag taskflow:latest
    - name: Check Build Result
      run: docker images
