name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run MySql
      run: docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 mysql:8.0
