# This is a basic workflow to help you get started with Actions

name: image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
runs:
  using: docker
  image: 'taskflow/Dockerfile'
