name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Files
      run: ls -l
    - name: Build the Docker image
      run: docker build --tag taskflow:latest .
    - name: Check Build Result
      run: docker images
    - name: Run Services
      run: docker-compose up -d
    - name: Check Services
      run: |
        sleep 30s
        docker ps
    - name: Init Data
      run: |
        docker cp docs/taskflowdb.sql db:/tmp/taskflowdb.sql
        docker exec db bash -c "mysql -uroot -p\$MYSQL_ROOT_PASSWORD < /tmp/taskflowdb.sql"
        docker exec db bash -c "mysql -uroot -p\$MYSQL_ROOT_PASSWORD -Dtaskflowdb -e 'show tables'"
    - name: Restart Services
      run: |
        docker exec taskflow bash -c "supervisorctl restart all"
        sleep 10s
        docker exec taskflow bash -c "supervisorctl status"
    - name: Run Tests
      run: |
        echo "check directory"
        docker exec taskflow bash -c "ls -la"
        echo "check python version"
        docker exec taskflow bash -c "python3 --version"
        echo "start tests"
        docker exec taskflow bash -c "python3 -m pytest -v tests -s"