name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Files
      run: ls -l
    - name: Build the Docker image
      run: docker build --tag taskflow:latest .
    - name: Check Build Result
      run: docker images
    - name: Run Services
      run: docker-compose up -d
    - name: Check Services
      run: docker ps
    - name: Run Tests
      run: |
        echo 'wait 15s for mysqld'
        sleep 15s
        docker cp docs/taskflowdb.sql db:/tmp/taskflowdb.sql
        docker exec db bash -c "mysql -uroot -p\$MYSQL_ROOT_PASSWORD < /tmp/taskflowdb.sql"
        docker exec taskflow bash -c "ls -la"
        docker exec taskflow bash -c "python3 --version"        
        docker exec taskflow bash -c "python3 -m pytest -v tests -s"