name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Show Files
      run: ls -l
    - name: Build Image
      run: docker build --tag taskflow:latest .
    - name: Show Images
      run: docker images
    - name: Run Docker Compose
      run: docker-compose up -d
    - name: Check Docker Services
      run: |
        sleep 30s
        docker ps
    - name: Init Data
      run: |
        docker cp docs/taskflowdb.sql db:/tmp/taskflowdb.sql
        docker exec db bash -c "mysql -uroot -p\$MYSQL_ROOT_PASSWORD < /tmp/taskflowdb.sql"
        docker exec db bash -c "mysql -uroot -p\$MYSQL_ROOT_PASSWORD -Dtaskflowdb -e 'show tables'"
    - name: Check Taskflow Services
      run: |
        sleep 10s
        docker exec taskflow bash -c "supervisorctl status"
    - name: Run Tests
      run: docker exec taskflow bash -c "python3 -m unittest discover"
