name: unittest
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Files
      run: ls -l
    - name: Build the Docker image
      run: docker build --tag taskflow:latest .
    - name: Check Build Result
      run: docker images
    - name: Run Services
      run: docker-compose up -d
    - name: Check Services
      run: docker ps
    - name: Run Tests
      run: |
        docker cp docs/taskflowdb.sql task-db:/tmp/taskflowdb.sql
        ps -ef
        docker exec task-db bash -c "ls -la /var/lib/mysql"
        docker exec task-db bash -c "mysql -hlocalhost -P3306 -uroot -p\$MYSQL_ROOT_PASSWORD < /tmp/taskflowdb.sql"
        docker exec task-service bash -c "ls -l"
        docker exec task-service bash -c "python3 --version"        
        docker exec task-service bash -c "python3 -m pytest -v tests"