name: unittest
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check Files
      run: ls -l
    - name: Build the Docker image
      run: docker build --tag taskflow:latest .
    - name: Check Build Result
      run: docker images
    - name: Run Services
      run: docker-compose up -d
    - name: Check Services
      run: docker ps
    - name: Run Tests
      run: docker exec -it task-service python3 -m pytest -v tests
